Telescope:
  - device_name: Ganymede
    ip: 127.0.0.1:80
    device_number: 0
    alt_limit: 20
Focuser:
  - device_name: focuser_Ganymede
    ip: 127.0.0.1:80
    device_number: 0
    focus_pos: 10000
Camera:
  - device_name: vis_cam_Ganymede
    ip: 127.0.0.1:80
    device_number: 0
    target_adu: [45000, 3000]
    paired_devices: 
      Telescope: Ganymede
      Focuser: focuser_Ganymede
      FilterWheel: vis_fw_Ganymede
      Dome: dome_Ganymede
      ObservingConditions: boltwood_Ganymede
      SafetyMonitor: boltwood_Ganymede
FilterWheel:
  - device_name: vis_fw_Ganymede
    ip: 127.0.0.1:80 
    device_number: 0
Dome:
  - device_name: dome_Ganymede
    ip: 127.0.0.1:80
    device_number: 0
ObservingConditions:
  - device_name: boltwood_Ganymede
    ip: 127.0.0.1:80
    device_number: 0
SafetyMonitor:
  - device_name: boltwood_Ganymede
    ip: 127.0.0.1:80
    device_number: 0
Misc:
  Webcam:
    rtsp: rtsp://username:password@192.168.1.108/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif